#!/usr/bin/env bash
set -e

if [ "$1" = "--debug" ]; then
  export ENV_DEBUG=1
  shift
fi

if [ -n "$ENV_DEBUG" ]; then
  export PS4='+ [${BASH_SOURCE##*/}:${LINENO}] '
  set -x
fi

abort() {
  { if [ "$#" -eq 0 ]; then cat -
    else echo "$binary: $*"
    fi
  } >&2
  exit 1
}

READLINK=$(type -p greadlink readlink | head -1)
[ -n "$READLINK" ] || abort "cannot find readlink - are you missing GNU coreutils?"

resolve_link() {
  $READLINK "$1"
}

abs_dirname() {
  local cwd="$PWD"
  local path="$1"

  while [ -n "$path" ]; do
    cd "${path%/*}"
    local name="${path##*/}"
    path="$(resolve_link "$name" || true)"
  done

  pwd
  cd "$cwd"
}

# http://stackoverflow.com/questions/1055671/how-can-i-get-the-behavior-of-gnus-readlink-f-on-a-mac
readlink_f() {
  local target_file="${1}"
  local file_name

  while [ "${target_file}" != "" ]; do
    cd "$(dirname ${target_file})"
    file_name="$(basename "${target_file}")"
    target_file="$(readlink "${file_name}")"
  done

  echo "$(pwd -P)/${file_name}"
}

if [ -z "${GLOBALENV_ROOT}" ]; then
  GLOBALENV_ROOT="$(cd "$(dirname "$(readlink_f "${0}")")/.." && pwd)"
else
  GLOBALENV_ROOT="${GLOBALENV_ROOT%/}"
fi
export GLOBALENV_ROOT

if [ -z "${GLOBALENV_DIR}" ]; then
  GLOBALENV_DIR="$PWD"
else
  [[ $GLOBALENV_DIR == /* ]] || GLOBALENV_DIR="$PWD/$GLOBALENV_DIR"
  cd "$GLOBALENV_DIR" 2>/dev/null || abort "cannot change working directory to \`$GLOBALENV_DIR'"
  GLOBALENV_DIR="$PWD"
  cd "$OLDPWD"
fi
export GLOBALENV_DIR


shopt -s nullglob

bin_path="$(abs_dirname "$0")"
export PATH="${bin_path}:${PATH}"

shopt -u nullglob

binary="$(basename $0)"
command="$1"
case "$command" in
"" )
  { binary=$binary env---version
    binary=$binary env-help
  } | abort
  ;;
-v | --version )
  binary=$binary exec env---version
  ;;
-h | --help )
  binary=$binary exec env-help
  ;;
* )
  command_path="$(command -v "env-$command" || true)"
  if [ -z "$command_path" ]; then
    if [ "$command" == "shell" ]; then
      abort "shell integration not enabled. Run \`$binary init' for instructions."
    else
      abort "no such command \`$command'"
    fi
  fi

  shift 1
  if [ "$1" = --help ]; then
    if [[ "$command" == "sh-"* ]]; then
      echo "$binary help \"$command\""
    else
      binary=$binary exec env-help "$command"
    fi
  else
      binary=$binary exec "$command_path" "$@"
  fi
  ;;
esac
